/* Comando para criação de tabelas de usuários */
CREATE TABLE USERS(
  USRID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  USRNAME VARCHAR(150) NOT NULL,
  URSDESC TEXT NOT NULL,
  USREMAIL VARCHAR(256) NOT NULL,
  USERPASSWORD VARCHAR(50) NOT NULL
);

/* Comando para criação da tabela de artistas */
CREATE TABLE ARTIST(
  ARTID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ARTNAME VARCHAR(150) NOT NULL,
  ARTDTBIRTH DATE NOT NULL,
  ARTDTDEATH DATE,
  ARTDTSTAR DATE NOT NULL,
  ARTDTEND DATE,
  ARTMINPIC TEXT NOT NULL,
  ARTLARPIC TEXT NOT NULL
);

/* Comando para criação da tabela de bandas */
CREATE TABLE BAND(
  BANID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  BANNAME VARCHAR(150) NOT NULL,
  BANDTBIRTH DATE NOT NULL,
  BANDTSTAR DATE NOT NULL,
  BANDTEND DATE,
  BANMINPIC TEXT NOT NULL,
  BANLARPIC TEXT NOT NULL
);

/* Comando para criação da tabela de genêros */
CREATE TABLE GENDER(
  GENID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  GENNAME VARCHAR(150) NOT NULL,
  GENDESC TEXT NOT NULL
);

/* Comando para criação da tabela de integrantes */
CREATE TABLE INTERNAL(
  INTARTIST INT NOT NULL,
  INTBAND INT NOT NULL,
  INTDTIN DATE NOT NULL,
  INTDTOUT DATE NOT NULL,
  FOREIGN KEY(INTARTIST) REFERENCES ARTIST(ARTID),
  FOREIGN KEY(INTBAND) REFERENCES BAND(BNDID)
);

/* Comando para criação da tabela de musicas com chave estrangeira para as tabela banda e artistas */
CREATE TABLE MUSIC(
  MSCID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  MSCNAME VARCHAR(150) NOT NULL,
  MSCBND INT NOT NULL,
  MSCART INT NOT NULL,
  MSCFEATBND INT NOT NULL,
  MSCFEATART INT NOT NULL,
  FOREIGN KEY(MSCBND) REFERENCES BAND(BNDID),
  FOREIGN KEY(MSCART) REFERENCES ARTIST(ARTID),
  FOREIGN KEY(MSCFEATBND) REFERENCES BAND(BNDID),
  FOREIGN KEY(MSCFEATART) REFERENCES ARTIST(ARTID)
);

/* Comando para criação da tabela de album com chave estrangeira para as tabela banda e artistas */
CREATE TABLE ALBUM(
  ALBID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  ALBNAME VARCHAR(150) NOT NULL,
  ALBARTIST INT NOT NULL,
  ALBBAND INT NOT NULL,
  ALBFEAT INT NOT NULL,
  ALBDTRELEASE DATE NOT NULL, 
  FOREIGN KEY(ALBBAND) REFERENCES BAND(BNDID),
  FOREIGN KEY(ALBARTIST) REFERENCES ARTIST(ARTID),
  FOREIGN KEY(ALBFEAT) REFERENCES BAND(BNDID),
  FOREIGN KEY(ALBFEAT) REFERENCES ARTIST(ARTID)
);

/* Comando para criação da tabela de faixas */
CREATE TABLE TRACK(
  RNGALBUM INT NOT NULL,
  RNGMUSIC INT NOT NULL,
  RNGNUMBER INT NOT NULL,
  FOREIGN KEY(RNGALBUM) REFERENCES ALBUM(ALBID),
  FOREIGN KEY(RNGMUSIC) REFERENCES MUSIC(MSCID)
)


/* Comando para criação da tabela de multiplos generos com chave estrangeira para as tabelas de música, banda, artista e album */
CREATE TABLE MULTIGEN(
  MTGALB INT,
  MTGART INT,
  MTGBND INT,
  MTGMSC INT,
  MTGGENDER INT NOT NULL,
  FOREIGN KEY(MTGALB) REFERENCES ALBUM(ALBID),
  FOREIGN KEY(MTGART) REFERENCES ARTIST(ARTID),
  FOREIGN KEY(MTGBND) REFERENCES BAND(BNDID),
  FOREIGN KEY(MTGMSC) REFERENCES MUSIC(MSCID),
  FOREIGN KEY(MTGGENDER) REFERENCES GENDER(GENID)
);

/* Comando para criação da tabela de seguidores */
CREATE TABLE FAVORITE(
  FAVUSER INT NOT NULL,
  FAVARTIST INT,
  FAVBAND INT,
  FAVALBUM INT,
  FAVMUSIC INT,
  FOREIGN KEY(FAVALBUM) REFERENCES ALBUM(ALBID),
  FOREIGN KEY(FAVARTIST) REFERENCES ARTIST(ARTID),
  FOREIGN KEY(FAVBAND) REFERENCES BAND(BNDID),
  FOREIGN KEY(FAVMUSIC) REFERENCES MUSIC(MSCID),
  FOREIGN KEY(FAVUSER) REFERENCES USER(USRID)
);